  - name: Install dependencies
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    ignore_errors: yes

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Get the version of ubuntu
    shell: grep "UBUNTU_CODENAME" /etc/os-release | cut -d= -f2 >> main.txt
    register: version

  - name: Add Docker repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable
      state: present

  - name: Install Docker
    apt:
      name: docker-ce
      state: present

  - name: Install Docker Compose
    get_url:
      url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

  - name: Set permissions for Docker Compose
    file:
      path: /usr/local/bin/docker-compose
      mode: 'a+x'
    
